language: python

cache: 
  pip: True

sudo: false

jobs:
    include:
    - name: python 3.9 linux
      os: linux
      python: 3.9
      stage: test
      script:
        - ./ci-test.sh
    - name: python 3.9 macos
      os: osx
      osx_image: xcode11.6
      language: shell
      before_install:
        brew install mysql
      stage: test
      script:
        - ./ci-test.sh

install:
    pip3 install --upgrade pip virtualenv

addons:
  homebrew:
    packages:
      - mysql

branches:
    only:
    - master
    - /^v/

services:
    - mysql
