language: python
cache: 
  pip: True

sudo: false

python:
  - 3.6
  - 3.9

jobs:
    include:
    - name: test
      stage: test

script:
  - ./ci-test.sh

after_success:
  - ./ci-cov.sh

branches:
  only:
  - master
  - /^v/

services:
    - mysql
