name: pytest

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ${{ matrix.info.os }}
    strategy:
      matrix:
        info:
          - os: ubuntu-latest
            python: 3.9
            mysql: 8.0
          - os: ubuntu-latest
            python: 3.7
            mysql: 8.0
          - os: windows-2022
            python: 3.9
            mysql: 5.7
    name: ${{matrix.info.os}} ${{ matrix.info.python }} ${{ matrix.info.mysql }}
    steps:
    - uses: actions/checkout@v2
    - uses: ankane/setup-mysql@v1
      with:
        mysql-version: ${{ matrix.info.mysql }}
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.info.python }}
      with:
        python-version: ${{ matrix.info.python }}
    - name: Deps
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        bash ./ci-test.sh
        bash ./ci-cov.sh
      env:
        COVERAGE_FILE ".coverage.${{ matrix.info.os }}.${{ matrix.info.python }}.${{ matrix.info.mysql }}"
    - uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: ${{ env.COVERAGE_FILE }}
  coverage:
      name: Coverage
      runs-on: ubuntu-latest
      needs: ci
      permissions:
        pull-requests: write
        contents: write
      steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: coverage
        - uses: py-cov-action/python-coverage-comment-action@v3
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MERGE_COVERAGE_FILES: true
        - uses: actions/upload-artifact@v3
          if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
          with: 
            name: coverage
            path: python-coverage-comment-action.txt


# vim: ts=2 sts=2 sw=2 et
