name: pytest

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.9]
    name: ${{matrix.os}} ${{ matrix.python }}
    steps:
    - uses: actions/checkout@v2
    - uses: ankane/setup-mysql@v1
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python }}
      with:
        python-version: ${{ matrix.python }}
    - name: Deps
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        ./ci-test.sh
        ./ci-cov.sh
