name: pytest

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        info:
          - os: [ubuntu-latest]
            python: 3.9
            mysql: 8.0
          - os: [ubuntu-latest]
            python: 3.6
            mysql: 8.0
          - os: [ubuntu-18.04]
            python: 3.9
            mysql: 5.7
    name: ${{matrix.info.os}} ${{ matrix.info.python }} ${{ matrix.info.mysql }}
    steps:
    - uses: actions/checkout@v2
    - uses: ankane/setup-mysql@v1
      with:
        mysql-version: ${{ matrix.mysql }}
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python }}
      with:
        python-version: ${{ matrix.python }}
    - name: Deps
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        ./ci-test.sh
        ./ci-cov.sh
